package service

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// codexWSIdentityCompatibilityKey returns a stable, non-reversible key for
// the client-owned Codex installation/session/thread identity.  Pooled
// sockets must not be shared by two genuine CLI clients merely because their
// beta feature sets match; the upstream socket carries continuation state.
// The key intentionally excludes turn-scoped fields (turn_id/window_id) so a
// single CLI session can reuse its socket across turns.
func codexWSIdentityCompatibilityKey(account *Account, c *gin.Context, headers http.Header, body []byte) (string, bool) {
	var inbound http.Header
	if c != nil && c.Request != nil {
		inbound = c.Request.Header
	}
	// parent_thread_id is a stable continuation boundary for Codex agent
	// sessions. It is not generated by the convergence modes, but when the
	// client supplies it, sockets carrying different parents must never share
	// upstream continuation state.
	inboundParentThreadID := firstHeaderValue(inbound, "x-codex-parent-thread-id", "parent_thread_id")
	outboundParentThreadID := firstHeaderValue(headers, "x-codex-parent-thread-id", "parent_thread_id")
	if inboundParentThreadID != "" && outboundParentThreadID != "" && inboundParentThreadID != outboundParentThreadID {
		return "", true
	}
	parentThreadID := inboundParentThreadID
	if parentThreadID == "" {
		parentThreadID = outboundParentThreadID
	}
	if projection := codexIdentityFromBody(body); projection.valid {
		if bodyParent := strings.TrimSpace(projection.tuple.parentThreadID); bodyParent != "" {
			if parentThreadID != "" && parentThreadID != bodyParent {
				// Contradictory carriers cannot be assigned a reusable pool key.
				// Keep this request isolated; the strict projection gate will handle
				// the body/header mismatch for the actual outbound request.
				return "", true
			}
			parentThreadID = bodyParent
		}
	} else if metadata := gjson.GetBytes(body, "client_metadata"); metadata.Exists() && metadata.IsObject() {
		// A malformed nested projection still carries stateful intent. Do not
		// assign it a reusable key because the surviving parent could disagree
		// with a flat carrier that the strict request gate will later reject.
		if firstNonEmptyGJSONString(metadata.Get("x-codex-parent-thread-id"), metadata.Get("parent_thread_id")) != "" {
			return "", true
		}
	}
	// Explicit account convergence owns the socket identity. Keep the stable
	// installation/session/thread tuple in the pool key while excluding the
	// per-turn UUID/timestamp, so subsequent turns can reuse their connection.
	if ids := stagedCodexFingerprintIDs(c, account); ids != nil {
		sessionID := strings.TrimSpace(ids.sessionID)
		if sessionID == "" {
			sessionID = firstHeaderValue(inbound, "session-id", "session_id", "conversation_id")
		}
		threadID := strings.TrimSpace(ids.threadID)
		if threadID == "" {
			threadID = firstHeaderValue(inbound, "thread-id", "thread_id")
		}
		if sessionID == "" {
			// prompt_cache_key is a cache domain, not a Codex session carrier.
			// Using it as a pool key can bind unrelated clients to one stateful
			// socket when they share a cache key.
			sessionID = firstBodyString(body, "client_metadata.session_id")
		}
		// A relay may retain only the nested turn-metadata projection, and a
		// mixed client can still send one flat field. Fill each missing carrier
		// independently from the same validated projection so a present thread
		// header does not hide the nested session (or vice versa).
		if projection := codexIdentityFromBody(body); projection.valid {
			if sessionID == "" {
				sessionID = strings.TrimSpace(projection.tuple.sessionID)
			}
			if threadID == "" {
				threadID = strings.TrimSpace(projection.tuple.threadID)
			}
		}
		// Device mode intentionally owns only installation_id. If the caller did
		// not provide any conversation carrier, a key based on the account and
		// installation alone would make unrelated downstream clients share the
		// same stateful upstream socket. Keep that request isolated until a
		// preferred continuation binding is available.
		if codexFingerprintRuntimeMode(ids.mode) == codexFingerprintDevice && sessionID == "" && threadID == "" {
			return "", true
		}
		mode := codexFingerprintRuntimeMode(ids.mode)
		scope := ""
		// All opt-in convergence modes can carry stateful upstream continuation
		// data. Keep their pool entries scoped to the downstream API key so two
		// users cannot share a socket merely because an account-owned session or
		// thread projection is identical. Turn-scoped fields remain excluded
		// from material below, preserving reuse across turns for one API key.
		apiKeyID := getAPIKeyIDFromContext(c)
		switch mode {
		case codexFingerprintSession, codexFingerprintFull:
			// Session/full convergence is stateful across turns. Without a
			// downstream API key there is no tenant scope to bind that state to;
			// force an isolated dial instead of reusing an account-wide socket.
			if apiKeyID <= 0 {
				return "", true
			}
			scope = fmt.Sprintf("apikey:%d", apiKeyID)
		case codexFingerprintDevice:
			if apiKeyID <= 0 {
				// Device mode preserves the caller's conversation identity. Without
				// a downstream API-key tenant boundary, reusing a stable socket could
				// join two users that happen to present the same session/thread IDs.
				return "", true
			}
			scope = fmt.Sprintf("apikey:%d", apiKeyID)
		}
		material := strings.Join([]string{
			fmt.Sprintf("account:%d", account.ID),
			string(mode),
			strings.TrimSpace(ids.installationID),
			sessionID,
			threadID,
			parentThreadID,
			scope,
		}, "\x00")
		digest := sha256.Sum256([]byte(material))
		return fmt.Sprintf("codex:%x", digest[:]), false
	}
	preserveIdentity := shouldPreserveCodexClientIdentityForRequestWithBody(c, account, inbound, body)
	if !preserveIdentity {
		// A relay may strip the strict UA/header triplet while retaining a
		// client_metadata lifecycle tuple. For OAuth off-mode requests, that
		// tuple is still enough to partition stateful sockets; it must not fall
		// back to the account-wide generic pool.
		bodyOrHeaderCarrier := account != nil && account.IsOpenAIOAuth() && hasCodexFingerprintIdentityCarrier(inbound, body)
		if !bodyOrHeaderCarrier {
			return "", false
		}
		headerProjection := codexIdentityFromHeaders(inbound)
		bodyProjection := codexIdentityFromBody(body)
		installationAgree := headerProjection.tuple.installationID == "" ||
			bodyProjection.tuple.installationID == "" ||
			headerProjection.tuple.installationID == bodyProjection.tuple.installationID
		if !headerProjection.valid || !bodyProjection.valid || !installationAgree ||
			!codexIdentityLifecycleTuplesAgree(headerProjection.tuple, bodyProjection.tuple) {
			if getAPIKeyIDFromContext(c) <= 0 {
				return "", true
			}
			return "", false
		}
	}

	installationID := firstHeaderValue(headers, "x-codex-installation-id")
	sessionID := firstHeaderValue(headers, "session-id", "session_id")
	threadID := firstHeaderValue(headers, "thread-id", "thread_id")
	metadata := firstHeaderValue(headers, "x-codex-turn-metadata")
	if installationID == "" {
		installationID = firstBodyString(body,
			"client_metadata.x-codex-installation-id",
			"client_metadata.installation_id",
		)
	}
	if projection := codexIdentityFromBody(body); projection.valid {
		if sessionID == "" {
			sessionID = strings.TrimSpace(projection.tuple.sessionID)
		}
		if threadID == "" {
			threadID = strings.TrimSpace(projection.tuple.threadID)
		}
	}
	if metadata != "" {
		if installationID == "" {
			installationID = firstBodyString([]byte(metadata), "installation_id")
		}
		if sessionID == "" {
			sessionID = firstBodyString([]byte(metadata), "session_id")
		}
		if threadID == "" {
			threadID = firstBodyString([]byte(metadata), "thread_id")
		}
	}
	if installationID == "" && sessionID == "" && threadID == "" {
		// A request can still be recognized as official by UA alone.  It has no
		// stable client identity, so callers must force a fresh socket rather than
		// risk sharing continuation state with another such client.
		return "", true
	}
	scope := ""
	if apiKeyID := getAPIKeyIDFromContext(c); apiKeyID > 0 {
		scope = fmt.Sprintf("apikey:%d", apiKeyID)
	} else {
		// The passthrough/off path retains client-owned lifecycle state. Without
		// a tenant key, force a fresh socket rather than sharing that state across
		// otherwise indistinguishable downstream callers.
		return "", true
	}
	material := strings.Join([]string{installationID, sessionID, threadID, parentThreadID, scope}, "\x00")
	digest := sha256.Sum256([]byte(material))
	// A stable identity key lets the pool reuse the same socket for subsequent
	// turns. Only the no-identity branch above needs a fresh connection.
	return fmt.Sprintf("codex:%x", digest[:]), false
}

// openAIWSIdentityAcquirePolicy keeps a client without a stable Codex
// identity isolated from unrelated pooled sockets while still honoring an
// explicit continuation binding.  ForceNewConn and ForcePreferredConn are
// mutually exclusive at the pool boundary: forcing a new connection causes
// the pool to ignore PreferredConnID entirely.  Callers therefore use the
// exact preferred socket when one is available, and only force a fresh dial
// for an unbound request.
func openAIWSIdentityAcquirePolicy(identityNeedsFreshConn bool, preferredConnID string, forcePreferredConn bool, dedicatedMode bool) (forceNewConn bool, forcePreferred bool) {
	preferredConnID = strings.TrimSpace(preferredConnID)
	forcePreferred = forcePreferredConn
	if identityNeedsFreshConn && preferredConnID != "" {
		forcePreferred = true
	}
	forceNewConn = dedicatedMode || (identityNeedsFreshConn && preferredConnID == "")
	return forceNewConn, forcePreferred
}

func validateOpenAIWSBearerToken(account *Account, token string) error {
	if account == nil {
		return errors.New("account is nil")
	}
	if strings.TrimSpace(token) == "" && !account.IsOpenAIAgentIdentity() {
		return errors.New("token is empty")
	}
	return nil
}

func (s *OpenAIGatewayService) buildOpenAIResponsesWSURL(account *Account) (string, error) {
	if account == nil {
		return "", errors.New("account is nil")
	}
	var targetURL string
	switch account.Type {
	case AccountTypeOAuth:
		targetURL = chatgptCodexURL
	case AccountTypeSetupToken:
		if account.IsOpenAIOAuthLike() {
			targetURL = chatgptCodexURL
		} else {
			targetURL = openaiPlatformAPIURL
		}
	case AccountTypeAPIKey:
		baseURL := account.GetOpenAIBaseURL()
		if account.UsesNativeCNResponses() && account.IsAdaptiveAPIProtocol() {
			baseURL = account.GetCNProtocolBaseURL(APIProtocolResponses)
		}
		if baseURL == "" {
			targetURL = openaiPlatformAPIURL
		} else {
			validatedURL, err := s.validateUpstreamBaseURL(baseURL)
			if err != nil {
				return "", err
			}
			targetURL = buildOpenAIResponsesURLForPlatform(account.Platform, validatedURL)
		}
	default:
		targetURL = openaiPlatformAPIURL
	}

	parsed, err := url.Parse(strings.TrimSpace(targetURL))
	if err != nil {
		return "", fmt.Errorf("invalid target url: %w", err)
	}
	switch strings.ToLower(parsed.Scheme) {
	case "https":
		parsed.Scheme = "wss"
	case "http":
		parsed.Scheme = "ws"
	case "wss", "ws":
		// 保持不变
	default:
		return "", fmt.Errorf("unsupported scheme for ws: %s", parsed.Scheme)
	}
	return parsed.String(), nil
}

func (s *OpenAIGatewayService) buildOpenAIWSHeaders(
	ctx context.Context,
	c *gin.Context,
	account *Account,
	token string,
	decision OpenAIWSProtocolDecision,
	isCodexCLI bool,
	turnState string,
	turnMetadata string,
	promptCacheKey string,
	routingModel string,
	routingServiceTier string,
) (http.Header, openAIWSSessionHeaderResolution, error) {
	return s.buildOpenAIWSHeadersWithBody(
		ctx,
		c,
		account,
		token,
		decision,
		isCodexCLI,
		turnState,
		turnMetadata,
		promptCacheKey,
		routingModel,
		routingServiceTier,
		nil,
	)
}

// buildOpenAIWSHeadersWithBody is the body-aware variant used by ingress
// paths. The official CLI carries the stable identity in client_metadata as
// well as headers; retaining the body here prevents a relay that strips
// canonical session headers from triggering synthetic identity rewriting.
func (s *OpenAIGatewayService) buildOpenAIWSHeadersWithBody(
	ctx context.Context,
	c *gin.Context,
	account *Account,
	token string,
	decision OpenAIWSProtocolDecision,
	isCodexCLI bool,
	turnState string,
	turnMetadata string,
	promptCacheKey string,
	routingModel string,
	routingServiceTier string,
	identityBody []byte,
) (http.Header, openAIWSSessionHeaderResolution, error) {
	headers := make(http.Header)
	// The first response.create frame may be the only remaining carrier of an
	// official CLI session after a relay has normalized its handshake headers.
	// Stage it before any response state is accepted or emitted on this socket.
	stageOpenAICodexTurnStateSession(c, identityBody)
	if account == nil || !account.IsOpenAIAgentIdentity() {
		headers.Set("authorization", "Bearer "+token)
	}

	sessionResolution := resolveOpenAIWSSessionHeaders(c, promptCacheKey)
	if c != nil && c.Request != nil {
		if v := strings.TrimSpace(c.Request.Header.Get("accept-language")); v != "" {
			headers.Set("accept-language", v)
		}
		for _, value := range c.Request.Header.Values("x-codex-beta-features") {
			if value = strings.TrimSpace(value); value != "" {
				headers.Add("x-codex-beta-features", value)
			}
		}
		for _, name := range [...]string{
			"user-agent",
			"openai-beta",
			"x-codex-window-id",
			"x-codex-installation-id",
			"x-codex-inference-call-id",
			"x-codex-turn-metadata",
			"x-codex-turn-state",
			"x-codex-parent-thread-id",
			"x-codex-routing-hint",
			"x-oai-attestation",
			"x-openai-internal-codex-residency",
			"x-openai-internal-codex-responses-lite",
			"x-openai-memgen-request",
			"x-responsesapi-include-timing-metrics",
			"x-openai-subagent",
			"session-id",
			"session_id",
			"thread-id",
			"thread_id",
			"x-client-request-id",
			"version",
			"conversation_id",
			"originator",
		} {
			if value := c.Request.Header.Get(name); strings.TrimSpace(value) != "" {
				headers.Set(name, value)
			}
		}
	}
	// The first response.create body can be the only surviving carrier of the
	// client lifecycle after an HTTP/WebSocket relay strips session/thread
	// headers. Restore its validated projections before this builder decides
	// whether to preserve or isolate the OAuth session aliases.
	restoreStagedCodexIdentityHeadersFromBody(c, account, headers, identityBody)
	canonicalSessionID := firstHeaderValue(headers, "session-id", "session_id")
	canonicalThreadID := firstHeaderValue(headers, "thread-id", "thread_id")
	canonicalRequestID := firstHeaderValue(headers, "x-client-request-id")
	canonicalConversationID := firstHeaderValue(headers, "conversation_id")
	// A state blob minted by a failed-over OAuth account is not valid for the
	// selected account. This mutates only the outbound handshake copy; the
	// client request headers remain untouched for retry/failover diagnostics.
	s.guardOpenAICodexTurnStateEcho(c, account, headers)
	applyOpenAICodexBetaFeatures(c, account, headers)

	// OAuth / SetupToken Codex: mix apiKeyID and credential namespace into
	// session identifiers so a failover cannot reuse another account's session.
	if account != nil && account.UsesOpenAICodexProtocol() {
		apiKeyID := getAPIKeyIDFromContext(c)
		hasFingerprintSnapshot := hasValidStagedCodexFingerprint(c, account)
		if shouldPreserveOutboundCodexClientSession(c, account) {
			sessionID := canonicalSessionID
			if sessionID == "" {
				sessionID = sessionResolution.SessionID
			}
			if sessionID != "" {
				headers.Set("session-id", sessionID)
				headers.Set("session_id", sessionID)
			}
			threadID := canonicalThreadID
			if threadID == "" {
				threadID = sessionID
			}
			if threadID != "" {
				headers.Set("thread-id", threadID)
				headers.Set("thread_id", threadID)
			}
			if canonicalRequestID != "" {
				headers.Set("x-client-request-id", canonicalRequestID)
			}
			conversationID := canonicalConversationID
			if conversationID != "" {
				headers.Set("conversation_id", conversationID)
			}
		} else {
			identitySource := codexAccountIdentitySource(c, account)
			if sessionResolution.SessionID != "" {
				headers.Set("session_id", isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, sessionResolution.SessionID))
			}
			if !hasFingerprintSnapshot && sessionResolution.ConversationID != "" {
				headers.Set("conversation_id", isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, sessionResolution.ConversationID))
			}
		}
	} else {
		if sessionResolution.SessionID != "" {
			headers.Set("session_id", sessionResolution.SessionID)
		}
		if sessionResolution.ConversationID != "" {
			headers.Set("conversation_id", sessionResolution.ConversationID)
		}
	}

	if strings.TrimSpace(headers.Get("session_id")) == "" {
		fallbackSession := strings.TrimSpace(sessionResolution.SessionID)
		if fallbackSession == "" {
			fallbackSession = strings.TrimSpace(promptCacheKey)
		}
		if fallbackSession != "" {
			if account != nil && account.UsesOpenAICodexProtocol() &&
				!shouldPreserveOutboundCodexClientSession(c, account) {
				fallbackSession = isolateOpenAIOAuthSessionValue(getAPIKeyIDFromContext(c), codexAccountIdentitySource(c, account), fallbackSession)
			}
			headers.Set("session_id", fallbackSession)
		}
	}
	if strings.TrimSpace(headers.Get("conversation_id")) == "" {
		fallbackConversation := ""
		if !hasValidStagedCodexFingerprint(c, account) {
			fallbackConversation = strings.TrimSpace(sessionResolution.ConversationID)
		}
		if fallbackConversation != "" {
			headers.Set("conversation_id", fallbackConversation)
		}
	}
	if shouldPreserveCodexClientSessionIdentityForRequest(c, account) {
		if strings.TrimSpace(headers.Get("session-id")) == "" {
			headers.Set("session-id", headers.Get("session_id"))
		}
		if strings.TrimSpace(headers.Get("thread-id")) == "" {
			headers.Set("thread-id", headers.Get("session_id"))
		}
		if strings.TrimSpace(headers.Get("thread_id")) == "" {
			headers.Set("thread_id", headers.Get("thread-id"))
		}
	}
	if state := strings.TrimSpace(turnState); state != "" && strings.TrimSpace(headers.Get(openAIWSTurnStateHeader)) == "" {
		headers.Set(openAIWSTurnStateHeader, state)
	}
	if metadata := strings.TrimSpace(turnMetadata); metadata != "" && strings.TrimSpace(headers.Get(openAIWSTurnMetadataHeader)) == "" {
		headers.Set(openAIWSTurnMetadataHeader, metadata)
	}
	if !shouldSkipCodexAccountIdentityRewrite(c, account, identityBody) {
		applyCodexAccountIdentityHeaders(headers, codexAccountIdentitySource(c, account), getAPIKeyIDFromContext(c))
	}
	// Preserve only client-supplied beta declarations here; v2 normalizes its
	// protocol beta at the final boundary below. Fingerprint headers are applied
	// after generic session isolation so session/full modes own the final IDs.
	if account != nil && account.UsesOpenAICodexProtocol() {
		if err := resolveAndSetOpenAIChatGPTAccountHeaders(ctx, s.accountRepo, headers, account); err != nil {
			return nil, sessionResolution, fmt.Errorf("resolve chatgpt account headers: %w", err)
		}
		headers.Set("originator", resolveOpenAIUpstreamOriginator(c, isCodexCLI))
		if !shouldPreserveOutboundCodexClientSession(c, account) {
			identitySource := codexAccountIdentitySource(c, account)
			apiKeyID := getAPIKeyIDFromContext(c)
			if isolated := isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, canonicalSessionID); isolated != "" {
				headers.Set("session-id", isolated)
				headers.Set("session_id", isolated)
			}
			if isolated := isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, canonicalThreadID); isolated != "" {
				headers.Set("thread-id", isolated)
				headers.Set("thread_id", isolated)
			} else if sessionID := strings.TrimSpace(headers.Get("session_id")); sessionID != "" {
				headers.Set("thread-id", sessionID)
				headers.Set("thread_id", sessionID)
			}
			if isolated := isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, canonicalRequestID); isolated != "" {
				headers.Set("x-client-request-id", isolated)
			} else if threadID := strings.TrimSpace(headers.Get("thread_id")); threadID != "" {
				headers.Set("x-client-request-id", threadID)
			}
			if isolated := isolateOpenAIOAuthSessionValue(apiKeyID, identitySource, canonicalConversationID); isolated != "" {
				headers.Set("conversation_id", isolated)
			}
		}
		// Apply the account lifecycle after generic session isolation so full and
		// session modes own the final session/thread/turn projection.
		applyStagedCodexFingerprintHeaders(c, account, headers)
	}

	// Normalize the protocol beta value after account-specific identity work.
	betaValue := openAIWSBetaV2Value
	if decision.Transport == OpenAIUpstreamTransportResponsesWebsocket {
		betaValue = openAIWSBetaV1Value
	}
	headers.Set("OpenAI-Beta", betaValue)

	customUA := ""
	if account != nil {
		customUA = account.GetOpenAIUserAgent()
	}
	if strings.TrimSpace(customUA) != "" {
		headers.Set("user-agent", customUA)
	} else if c != nil {
		if ua := strings.TrimSpace(c.GetHeader("User-Agent")); ua != "" {
			headers.Set("user-agent", ua)
		}
	}
	if s != nil && s.cfg != nil && s.cfg.Gateway.ForceCodexCLI {
		headers.Set("user-agent", CodexCanonicalUserAgent())
	}
	// 终态收口：WS 握手与 HTTP 出站共用同一套身份语义，账号级自定义 UA 同样作为
	// 管理员显式配置传入（上面写进 headers 的值只在强制统一被关闭时才参与配对）。
	if account != nil && account.UsesOpenAICodexProtocol() {
		enforceCodexIdentityHeadersWithUA(headers, s.codexIdentityOverrideUA(account))
	}

	// v2 keeps turn state and Responses Lite inside response.create. The
	// protocol normalizer injects the header-derived state/metadata payload.
	if decision.Transport == OpenAIUpstreamTransportResponsesWebsocketV2 {
		// The official CLI always upgrades v2 with this exact beta value. Turn
		// state and Responses Lite are per-response.create metadata in v2, never
		// handshake headers. Apply it after the inbound projection so the v2
		// protocol cannot be downgraded by a caller-provided OpenAI-Beta value.
		headers.Set("OpenAI-Beta", openAIWSBetaV2Value)
		headers.Del(openAIWSTurnStateHeader)
		headers.Del(responsesLiteHeaderKey)
	}
	account.ApplyHeaderOverrides(headers)
	setOpenAICodexRoutingHint(headers, account, routingModel, routingServiceTier)
	logOpenAIRoutingDiagnostics(
		ctx,
		account,
		string(decision.Transport),
		routingModel,
		routingServiceTier,
		strings.TrimSpace(headers.Get(openAICodexRoutingHintHeader)) != "",
		"soft_routing_hint",
	)

	return headers, sessionResolution, nil
}

func (s *OpenAIGatewayService) buildOpenAIWSCreatePayload(reqBody map[string]any, account *Account) map[string]any {
	// OpenAI WS Mode 协议：response.create 字段与 HTTP /responses 基本一致。
	// 保留 stream 字段（与 Codex CLI 一致），仅移除 background。
	payload := make(map[string]any, len(reqBody)+1)
	for k, v := range reqBody {
		payload[k] = v
	}

	delete(payload, "background")
	if _, exists := payload["stream"]; !exists {
		payload["stream"] = true
	}
	payload["type"] = "response.create"

	// OAuth 默认保持 store=false，避免误依赖服务端历史。
	if account != nil && account.UsesOpenAICodexProtocol() && !s.isOpenAIWSStoreRecoveryAllowed(account) {
		payload["store"] = false
	}
	return payload
}

const openAIWSStreamRequestStartMSMetadataKey = "x-codex-ws-stream-request-start-ms"

// openAIWSResponseCreateProtocolOptions contains only transport-scoped
// response.create metadata. It deliberately has no client identity fields:
// official Codex installation/session/thread identity remains client-owned.
type openAIWSResponseCreateProtocolOptions struct {
	TurnState     string
	TurnMetadata  string
	ResponsesLite bool
}

func openAIWSResponseCreateProtocolOptionsFromHeaders(headers http.Header, turnState string) openAIWSResponseCreateProtocolOptions {
	// A caller-provided header is authoritative. The explicit argument is used
	// for scheduler/state-store fallbacks only when the client omitted it.
	if headers != nil {
		if clientTurnState := strings.TrimSpace(firstHeaderValue(headers, openAIWSTurnStateHeader)); clientTurnState != "" {
			turnState = clientTurnState
		}
	}
	turnMetadata := ""
	if headers != nil {
		turnMetadata = strings.TrimSpace(firstHeaderValue(headers, openAIWSTurnMetadataHeader))
	}
	return openAIWSResponseCreateProtocolOptions{
		TurnState:     strings.TrimSpace(turnState),
		TurnMetadata:  turnMetadata,
		ResponsesLite: isOpenAIResponsesLiteHeader(firstHeaderValue(headers, responsesLiteHeaderKey)),
	}
}

// normalizeOpenAIWSResponseCreatePayload applies the transport metadata that
// the official Codex CLI sends on every Responses WebSocket response.create.
// It never manufactures or rewrites client identity fields. Body-carried turn
// state is authoritative, so a fallback/header state fills only an absent or
// empty value.
func normalizeOpenAIWSResponseCreatePayload(payload map[string]any, options openAIWSResponseCreateProtocolOptions) bool {
	if len(payload) == 0 || strings.TrimSpace(fmt.Sprintf("%v", payload["type"])) != "response.create" {
		return false
	}

	metadata := make(map[string]any)
	switch existing := payload["client_metadata"].(type) {
	case map[string]any:
		for key, value := range existing {
			metadata[key] = value
		}
	case map[string]string:
		for key, value := range existing {
			metadata[key] = value
		}
	}

	if existingState, _ := metadata[openAIWSTurnStateHeader].(string); strings.TrimSpace(existingState) == "" {
		if turnState := strings.TrimSpace(options.TurnState); turnState != "" {
			metadata[openAIWSTurnStateHeader] = turnState
		}
	}
	if existingMetadata, _ := metadata[openAIWSTurnMetadataHeader].(string); strings.TrimSpace(existingMetadata) == "" {
		if turnMetadata := strings.TrimSpace(options.TurnMetadata); turnMetadata != "" {
			metadata[openAIWSTurnMetadataHeader] = turnMetadata
		}
	}
	if options.ResponsesLite {
		if current, _ := metadata[responsesLiteWSMetadataKey].(string); current != "true" {
			metadata[responsesLiteWSMetadataKey] = "true"
		}
	}

	// The CLI stamps this immediately before each socket write, including
	// prewarm and retry frames. Always replace a stale client-provided value.
	metadata[openAIWSStreamRequestStartMSMetadataKey] = strconv.FormatInt(time.Now().UnixMilli(), 10)
	payload["client_metadata"] = metadata
	return true
}

// normalizeOpenAIWSResponseCreatePayloadBytes is the raw-frame equivalent
// used by native WebSocket ingress and passthrough filters. Non-response.create
// frames are left byte-for-byte unchanged.
func normalizeOpenAIWSResponseCreatePayloadBytes(
	payload []byte,
	options openAIWSResponseCreateProtocolOptions,
) ([]byte, bool, error) {
	if !gjson.ValidBytes(payload) {
		return payload, false, errors.New("invalid websocket response.create payload")
	}
	if strings.TrimSpace(gjson.GetBytes(payload, "type").String()) != "response.create" {
		return payload, false, nil
	}
	decoded := make(map[string]any)
	if err := decodeOpenAIJSONUseNumber(payload, &decoded); err != nil {
		return payload, false, err
	}
	if !normalizeOpenAIWSResponseCreatePayload(decoded, options) {
		return payload, false, nil
	}
	normalized, err := marshalOpenAIUpstreamJSON(decoded)
	if err != nil {
		return payload, false, err
	}
	return normalized, true, nil
}

func setOpenAIWSTurnMetadata(payload map[string]any, turnMetadata string) {
	if len(payload) == 0 {
		return
	}
	metadata := strings.TrimSpace(turnMetadata)
	if metadata == "" {
		return
	}

	switch existing := payload["client_metadata"].(type) {
	case map[string]any:
		existing[openAIWSTurnMetadataHeader] = metadata
		payload["client_metadata"] = existing
	case map[string]string:
		next := make(map[string]any, len(existing)+1)
		for k, v := range existing {
			next[k] = v
		}
		next[openAIWSTurnMetadataHeader] = metadata
		payload["client_metadata"] = next
	default:
		payload["client_metadata"] = map[string]any{
			openAIWSTurnMetadataHeader: metadata,
		}
	}
}

func (s *OpenAIGatewayService) isOpenAIWSStoreRecoveryAllowed(account *Account) bool {
	if account != nil && account.IsOpenAIWSAllowStoreRecoveryEnabled() {
		return true
	}
	if s != nil && s.cfg != nil && s.cfg.Gateway.OpenAIWS.AllowStoreRecovery {
		return true
	}
	return false
}

func (s *OpenAIGatewayService) isOpenAIWSStoreDisabledInRequest(reqBody map[string]any, account *Account) bool {
	if account != nil && account.UsesOpenAICodexProtocol() && !s.isOpenAIWSStoreRecoveryAllowed(account) {
		return true
	}
	if len(reqBody) == 0 {
		return false
	}
	rawStore, ok := reqBody["store"]
	if !ok {
		return false
	}
	storeEnabled, ok := rawStore.(bool)
	if !ok {
		return false
	}
	return !storeEnabled
}

func (s *OpenAIGatewayService) isOpenAIWSStoreDisabledInRequestRaw(reqBody []byte, account *Account) bool {
	if account != nil && account.UsesOpenAICodexProtocol() && !s.isOpenAIWSStoreRecoveryAllowed(account) {
		return true
	}
	if len(reqBody) == 0 {
		return false
	}
	storeValue := gjson.GetBytes(reqBody, "store")
	if !storeValue.Exists() {
		return false
	}
	if storeValue.Type != gjson.True && storeValue.Type != gjson.False {
		return false
	}
	return !storeValue.Bool()
}

func (s *OpenAIGatewayService) openAIWSStoreDisabledConnMode() string {
	if s == nil || s.cfg == nil {
		return openAIWSStoreDisabledConnModeStrict
	}
	mode := strings.ToLower(strings.TrimSpace(s.cfg.Gateway.OpenAIWS.StoreDisabledConnMode))
	switch mode {
	case openAIWSStoreDisabledConnModeStrict, openAIWSStoreDisabledConnModeAdaptive, openAIWSStoreDisabledConnModeOff:
		return mode
	case "":
		// 兼容旧配置：仅配置了布尔开关时按旧语义推导。
		if s.cfg.Gateway.OpenAIWS.StoreDisabledForceNewConn {
			return openAIWSStoreDisabledConnModeStrict
		}
		return openAIWSStoreDisabledConnModeOff
	default:
		return openAIWSStoreDisabledConnModeStrict
	}
}

func shouldForceNewConnOnStoreDisabled(mode, lastFailureReason string) bool {
	switch mode {
	case openAIWSStoreDisabledConnModeOff:
		return false
	case openAIWSStoreDisabledConnModeAdaptive:
		reason := strings.TrimPrefix(strings.TrimSpace(lastFailureReason), "prewarm_")
		switch reason {
		case "policy_violation", "message_too_big", "auth_failed", "write_request", "write":
			return true
		default:
			return false
		}
	default:
		return true
	}
}

func dropPreviousResponseIDFromRawPayload(payload []byte) ([]byte, bool, error) {
	return dropPreviousResponseIDFromRawPayloadWithDeleteFn(payload, sjson.DeleteBytes)
}

func dropPreviousResponseIDFromRawPayloadWithDeleteFn(
	payload []byte,
	deleteFn func([]byte, string) ([]byte, error),
) ([]byte, bool, error) {
	if len(payload) == 0 {
		return payload, false, nil
	}
	if !gjson.GetBytes(payload, "previous_response_id").Exists() {
		return payload, false, nil
	}
	if deleteFn == nil {
		deleteFn = sjson.DeleteBytes
	}

	updated := payload
	for i := 0; i < openAIWSMaxPrevResponseIDDeletePasses &&
		gjson.GetBytes(updated, "previous_response_id").Exists(); i++ {
		next, err := deleteFn(updated, "previous_response_id")
		if err != nil {
			return payload, false, err
		}
		updated = next
	}
	return updated, !gjson.GetBytes(updated, "previous_response_id").Exists(), nil
}

func setPreviousResponseIDToRawPayload(payload []byte, previousResponseID string) ([]byte, error) {
	normalizedPrevID := strings.TrimSpace(previousResponseID)
	if len(payload) == 0 || normalizedPrevID == "" {
		return payload, nil
	}
	updated, err := sjson.SetBytes(payload, "previous_response_id", normalizedPrevID)
	if err == nil {
		return updated, nil
	}

	var reqBody map[string]any
	if unmarshalErr := decodeOpenAIJSONUseNumber(payload, &reqBody); unmarshalErr != nil {
		return nil, err
	}
	reqBody["previous_response_id"] = normalizedPrevID
	rebuilt, marshalErr := json.Marshal(reqBody)
	if marshalErr != nil {
		return nil, marshalErr
	}
	return rebuilt, nil
}

func shouldInferIngressFunctionCallOutputPreviousResponseID(
	storeDisabled bool,
	turn int,
	signals ToolContinuationSignals,
	currentPreviousResponseID string,
	expectedPreviousResponseID string,
) bool {
	if !storeDisabled || turn <= 1 || !signals.HasFunctionCallOutput {
		return false
	}
	if strings.TrimSpace(currentPreviousResponseID) != "" {
		return false
	}
	if signals.HasFunctionCallOutputMissingCallID {
		return false
	}
	// If the client already sent the actual tool-call context, treat this as
	// a full replay / self-contained continuation payload rather than
	// downgrading it into an inferred delta continuation. item_reference alone
	// is not enough on the store=false WS path: it still needs a valid prior
	// response anchor so upstream can resolve the referenced function_call.
	if signals.HasToolCallContext {
		return false
	}
	return strings.TrimSpace(expectedPreviousResponseID) != ""
}

func alignStoreDisabledPreviousResponseID(
	payload []byte,
	expectedPreviousResponseID string,
) ([]byte, bool, error) {
	if len(payload) == 0 {
		return payload, false, nil
	}
	expected := strings.TrimSpace(expectedPreviousResponseID)
	if expected == "" {
		return payload, false, nil
	}
	current := openAIWSPayloadStringFromRaw(payload, "previous_response_id")
	if current == "" || current == expected {
		return payload, false, nil
	}

	withoutPrev, removed, dropErr := dropPreviousResponseIDFromRawPayload(payload)
	if dropErr != nil {
		return payload, false, dropErr
	}
	if !removed {
		return payload, false, nil
	}
	updated, setErr := setPreviousResponseIDToRawPayload(withoutPrev, expected)
	if setErr != nil {
		return payload, false, setErr
	}
	return updated, true, nil
}

func cloneOpenAIWSPayloadBytes(payload []byte) []byte {
	if len(payload) == 0 {
		return nil
	}
	cloned := make([]byte, len(payload))
	copy(cloned, payload)
	return cloned
}

func cloneOpenAIWSRawMessages(items []json.RawMessage) []json.RawMessage {
	if items == nil {
		return nil
	}
	cloned := make([]json.RawMessage, 0, len(items))
	for idx := range items {
		cloned = append(cloned, json.RawMessage(cloneOpenAIWSPayloadBytes(items[idx])))
	}
	return cloned
}

func normalizeOpenAIWSJSONForCompare(raw []byte) ([]byte, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		return nil, errors.New("json is empty")
	}
	var decoded any
	if err := decodeOpenAIJSONUseNumber(trimmed, &decoded); err != nil {
		return nil, err
	}
	return json.Marshal(decoded)
}

func normalizeOpenAIWSJSONForCompareOrRaw(raw []byte) []byte {
	normalized, err := normalizeOpenAIWSJSONForCompare(raw)
	if err != nil {
		return bytes.TrimSpace(raw)
	}
	return normalized
}

func normalizeOpenAIWSPayloadWithoutInputAndPreviousResponseID(payload []byte) ([]byte, error) {
	if len(payload) == 0 {
		return nil, errors.New("payload is empty")
	}
	var decoded map[string]any
	if err := decodeOpenAIJSONUseNumber(payload, &decoded); err != nil {
		return nil, err
	}
	delete(decoded, "input")
	delete(decoded, "previous_response_id")
	// Codex changes transport-only metadata for every response.create. These fields
	// do not alter the context referenced by previous_response_id and are excluded
	// from Codex's own websocket reuse comparison.
	delete(decoded, "client_metadata")
	delete(decoded, "stream_options")
	// Official Codex prewarms a connection with generate=false, then omits the
	// field on the business request that continues from the prewarm response.
	// Only normalize false so a meaningful generate=true change remains visible.
	if generate, ok := decoded["generate"].(bool); ok && !generate {
		delete(decoded, "generate")
	}
	return json.Marshal(decoded)
}

func openAIWSExtractNormalizedInputSequence(payload []byte) ([]json.RawMessage, bool, error) {
	if len(payload) == 0 {
		return nil, false, nil
	}
	inputValue := gjson.GetBytes(payload, "input")
	if !inputValue.Exists() {
		return nil, false, nil
	}
	if inputValue.Type == gjson.JSON {
		raw := strings.TrimSpace(inputValue.Raw)
		if strings.HasPrefix(raw, "[") {
			var items []json.RawMessage
			if err := json.Unmarshal([]byte(raw), &items); err != nil {
				return nil, true, err
			}
			return items, true, nil
		}
		return []json.RawMessage{json.RawMessage(raw)}, true, nil
	}
	if inputValue.Type == gjson.String {
		encoded, _ := json.Marshal(inputValue.String())
		return []json.RawMessage{encoded}, true, nil
	}
	return []json.RawMessage{json.RawMessage(inputValue.Raw)}, true, nil
}

func openAIWSInputIsPrefixExtended(previousPayload, currentPayload []byte) (bool, error) {
	previousItems, previousExists, prevErr := openAIWSExtractNormalizedInputSequence(previousPayload)
	if prevErr != nil {
		return false, prevErr
	}
	currentItems, currentExists, currentErr := openAIWSExtractNormalizedInputSequence(currentPayload)
	if currentErr != nil {
		return false, currentErr
	}
	if !previousExists && !currentExists {
		return true, nil
	}
	if !previousExists {
		return len(currentItems) == 0, nil
	}
	if !currentExists {
		return len(previousItems) == 0, nil
	}
	if len(currentItems) < len(previousItems) {
		return false, nil
	}

	for idx := range previousItems {
		previousNormalized := normalizeOpenAIWSJSONForCompareOrRaw(previousItems[idx])
		currentNormalized := normalizeOpenAIWSJSONForCompareOrRaw(currentItems[idx])
		if !bytes.Equal(previousNormalized, currentNormalized) {
			return false, nil
		}
	}
	return true, nil
}

func openAIWSRawItemsHasPrefix(items []json.RawMessage, prefix []json.RawMessage) bool {
	if len(prefix) == 0 {
		return true
	}
	if len(items) < len(prefix) {
		return false
	}
	for idx := range prefix {
		previousNormalized := normalizeOpenAIWSJSONForCompareOrRaw(prefix[idx])
		currentNormalized := normalizeOpenAIWSJSONForCompareOrRaw(items[idx])
		if !bytes.Equal(previousNormalized, currentNormalized) {
			return false
		}
	}
	return true
}

func openAIWSRawItemsHasFunctionCallOutput(items []json.RawMessage) bool {
	for _, item := range items {
		parsed := gjson.ParseBytes(item)
		if !isCodexSyntheticAgentContextJSONItem(parsed) && isCodexToolCallOutputItemType(parsed.Get("type").String()) {
			return true
		}
	}
	return false
}

func openAIWSRawItemsHaveToolCallContextForOutputs(items []json.RawMessage) bool {
	if len(items) == 0 {
		return false
	}
	contextCallIDs := make(map[string]struct{})
	outputCallIDs := make(map[string]struct{})
	for _, item := range items {
		parsed := gjson.ParseBytes(item)
		if isCodexSyntheticAgentContextJSONItem(parsed) {
			continue
		}
		itemType := parsed.Get("type").String()
		callID := strings.TrimSpace(parsed.Get("call_id").String())
		switch {
		case isCodexToolCallContextItemType(itemType):
			if callID != "" {
				contextCallIDs[callID] = struct{}{}
			}
		case isCodexToolCallOutputItemType(itemType):
			if callID == "" {
				return false
			}
			outputCallIDs[callID] = struct{}{}
		}
	}
	if len(outputCallIDs) == 0 || len(contextCallIDs) == 0 {
		return false
	}
	for callID := range outputCallIDs {
		if _, ok := contextCallIDs[callID]; !ok {
			return false
		}
	}
	return true
}

func sanitizeOpenAIWSHistoricalReplayToolCalls(
	previousItems []json.RawMessage,
	currentItems []json.RawMessage,
) []json.RawMessage {
	if len(previousItems) == 0 {
		return cloneOpenAIWSRawMessages(previousItems)
	}
	outputCallIDs := make(map[string]struct{})
	collectOutputCallIDs := func(items []json.RawMessage) {
		for _, item := range items {
			if !isCodexToolCallOutputItemType(gjson.GetBytes(item, "type").String()) {
				continue
			}
			if callID := strings.TrimSpace(gjson.GetBytes(item, "call_id").String()); callID != "" {
				outputCallIDs[callID] = struct{}{}
			}
		}
	}
	collectOutputCallIDs(previousItems)
	collectOutputCallIDs(currentItems)

	sanitized := make([]json.RawMessage, 0, len(previousItems))
	for _, item := range previousItems {
		if isCodexToolCallContextItemType(gjson.GetBytes(item, "type").String()) {
			callID := strings.TrimSpace(gjson.GetBytes(item, "call_id").String())
			if _, paired := outputCallIDs[callID]; !paired {
				continue
			}
		}
		sanitized = append(sanitized, append(json.RawMessage(nil), item...))
	}
	return sanitized
}

func openAIWSRawPayloadHasToolCallOutput(payload []byte) bool {
	if len(payload) == 0 {
		return false
	}
	input := gjson.GetBytes(payload, "input")
	if !input.Exists() {
		return false
	}
	if input.IsArray() {
		for _, item := range input.Array() {
			if !isCodexSyntheticAgentContextJSONItem(item) && isCodexToolCallOutputItemType(item.Get("type").String()) {
				return true
			}
		}
		return false
	}
	if input.Type == gjson.JSON {
		return !isCodexSyntheticAgentContextJSONItem(input) && isCodexToolCallOutputItemType(input.Get("type").String())
	}
	return false
}

func buildOpenAIWSReplayInputSequence(
	previousFullInput []json.RawMessage,
	previousFullInputExists bool,
	currentPayload []byte,
	hasPreviousResponseID bool,
) ([]json.RawMessage, bool, error) {
	currentItems, currentExists, currentErr := openAIWSExtractNormalizedInputSequence(currentPayload)
	if currentErr != nil {
		return nil, false, currentErr
	}
	if !hasPreviousResponseID {
		return cloneOpenAIWSRawMessages(currentItems), currentExists, nil
	}
	if !previousFullInputExists {
		return cloneOpenAIWSRawMessages(currentItems), currentExists, nil
	}
	previousFullInput = sanitizeOpenAIWSHistoricalReplayToolCalls(previousFullInput, currentItems)
	if !currentExists || len(currentItems) == 0 {
		return cloneOpenAIWSRawMessages(previousFullInput), true, nil
	}
	if openAIWSRawItemsHasPrefix(currentItems, previousFullInput) {
		return cloneOpenAIWSRawMessages(currentItems), true, nil
	}
	merged := make([]json.RawMessage, 0, len(previousFullInput)+len(currentItems))
	merged = append(merged, cloneOpenAIWSRawMessages(previousFullInput)...)
	merged = append(merged, cloneOpenAIWSRawMessages(currentItems)...)
	return merged, true, nil
}

func setOpenAIWSPayloadInputSequence(
	payload []byte,
	fullInput []json.RawMessage,
	fullInputExists bool,
) ([]byte, error) {
	if !fullInputExists {
		return payload, nil
	}
	// Preserve [] vs null semantics when input exists but is empty.
	inputForMarshal := fullInput
	if inputForMarshal == nil {
		inputForMarshal = []json.RawMessage{}
	}
	inputRaw, marshalErr := json.Marshal(inputForMarshal)
	if marshalErr != nil {
		return nil, marshalErr
	}
	return sjson.SetRawBytes(payload, "input", inputRaw)
}

func buildOpenAIWSCurrentTurnRetryPayload(
	payload []byte,
	fullInput []json.RawMessage,
	fullInputExists bool,
	originalModel string,
) ([]byte, bool, error) {
	if !fullInputExists {
		return nil, false, nil
	}
	retryPayload, err := setOpenAIWSPayloadInputSequence(payload, fullInput, true)
	if err != nil {
		return nil, false, err
	}
	retryPayload = RemovePreviousResponseIDFromBody(retryPayload)
	if model := strings.TrimSpace(originalModel); model != "" {
		retryPayload, err = sjson.SetBytes(retryPayload, "model", model)
		if err != nil {
			return nil, false, err
		}
	}
	coverage := AnalyzeToolCallOutputContextCoverageBytes(retryPayload)
	if coverage.HasFunctionCallOutput && !coverage.ContextCoversAllCallIDs {
		return nil, false, nil
	}
	return retryPayload, true, nil
}

func shouldKeepIngressPreviousResponseID(
	previousPayload []byte,
	currentPayload []byte,
	lastTurnResponseID string,
	hasFunctionCallOutput bool,
) (bool, string, error) {
	if hasFunctionCallOutput {
		return true, "has_function_call_output", nil
	}
	currentPreviousResponseID := strings.TrimSpace(openAIWSPayloadStringFromRaw(currentPayload, "previous_response_id"))
	if currentPreviousResponseID == "" {
		return false, "missing_previous_response_id", nil
	}
	expectedPreviousResponseID := strings.TrimSpace(lastTurnResponseID)
	if expectedPreviousResponseID == "" {
		return false, "missing_last_turn_response_id", nil
	}
	if currentPreviousResponseID != expectedPreviousResponseID {
		return false, "previous_response_id_mismatch", nil
	}
	if len(previousPayload) == 0 {
		return false, "missing_previous_turn_payload", nil
	}

	previousComparable, previousComparableErr := normalizeOpenAIWSPayloadWithoutInputAndPreviousResponseID(previousPayload)
	if previousComparableErr != nil {
		return false, "non_input_compare_error", previousComparableErr
	}
	currentComparable, currentComparableErr := normalizeOpenAIWSPayloadWithoutInputAndPreviousResponseID(currentPayload)
	if currentComparableErr != nil {
		return false, "non_input_compare_error", currentComparableErr
	}
	if !bytes.Equal(previousComparable, currentComparable) {
		return false, "non_input_changed", nil
	}
	return true, "strict_incremental_ok", nil
}

type openAIWSIngressPreviousTurnStrictState struct {
	nonInputComparable []byte
}

func buildOpenAIWSIngressPreviousTurnStrictState(payload []byte) (*openAIWSIngressPreviousTurnStrictState, error) {
	if len(payload) == 0 {
		return nil, nil
	}
	nonInputComparable, nonInputErr := normalizeOpenAIWSPayloadWithoutInputAndPreviousResponseID(payload)
	if nonInputErr != nil {
		return nil, nonInputErr
	}
	return &openAIWSIngressPreviousTurnStrictState{
		nonInputComparable: nonInputComparable,
	}, nil
}

func shouldKeepIngressPreviousResponseIDWithStrictState(
	previousState *openAIWSIngressPreviousTurnStrictState,
	currentPayload []byte,
	lastTurnResponseID string,
	hasFunctionCallOutput bool,
) (bool, string, error) {
	if hasFunctionCallOutput {
		return true, "has_function_call_output", nil
	}
	currentPreviousResponseID := strings.TrimSpace(openAIWSPayloadStringFromRaw(currentPayload, "previous_response_id"))
	if currentPreviousResponseID == "" {
		return false, "missing_previous_response_id", nil
	}
	expectedPreviousResponseID := strings.TrimSpace(lastTurnResponseID)
	if expectedPreviousResponseID == "" {
		return false, "missing_last_turn_response_id", nil
	}
	if currentPreviousResponseID != expectedPreviousResponseID {
		return false, "previous_response_id_mismatch", nil
	}
	if previousState == nil {
		return false, "missing_previous_turn_payload", nil
	}

	currentComparable, currentComparableErr := normalizeOpenAIWSPayloadWithoutInputAndPreviousResponseID(currentPayload)
	if currentComparableErr != nil {
		return false, "non_input_compare_error", currentComparableErr
	}
	if !bytes.Equal(previousState.nonInputComparable, currentComparable) {
		return false, "non_input_changed", nil
	}
	return true, "strict_incremental_ok", nil
}
